In [1]:
from __future__ import print_function

"""
A script to run cqed_rhf method on the formaldehyde coupled to a photon with 
different polarizations and coupling magnitude |\lambda| = 0.2 atomic units
to produce data from Table I of McTague and Foley 
"""

__authors__   = ["Jon McTague", "Jonathan Foley"]
__credits__   = ["Jon McTague", "Jonathan Foley"]

__copyright_amp__ = "(c) 2014-2018, The Psi4NumPy Developers"
__license__   = "BSD-3-Clause"
__date__      = "2021-01-15"

# ==> Import Psi4, NumPy, & SciPy <==
import psi4
import numpy as np
from helper_cqed_rhf import *
from helper_cs_cqed_cis import *
from matplotlib import pyplot as plt

# Set Psi4 & NumPy Memory Options
psi4.set_memory('2 GB')
psi4.core.set_output_file('output.dat', False)

numpy_memory = 2



  Memory set to   1.863 GiB by Python driver.


In [2]:

# rhf/cc-pVDZ optimized geometry of formaldehyde
molstr = """

0 1
O 0.0000000000 0.0000000000 5.91268220e-01
C 0.0000000000 0.0000000000 -5.90400099e-01
H 0.0000000000 9.32184336e-01 -1.17703144e+00
H 0.0000000000 -9.32184336e-01 -1.17703144e+00
no_reorient
symmetry c1
"""

# options dict
options_dict = {'basis': 'cc-pVDZ',
               'save_jk': True, 
               'scf_type': 'pk',
               'e_convergence' : 1e-8,
               'd_convergence' : 1e-7}

# to verify this geometry is optimal, you can run the block below
#psi4.set_options(options_dict)
#mol = psi4.geometry(molstr)

#opt_geometry = mol.geometry()
#print(opt_geometry.np*0.529)

Run the calculations below to compute the CQED-RHF energy for various polarizations and
without coupling to a photon.  

In [3]:
from numpy import linalg 
# different magnitudes of the lambda vector
l = 0.1


lam_y = np.array([0, l, 0])
lam_z = np.array([0, 0, l])
lam_yz = np.array([0, l/np.sqrt(2), l/np.sqrt(2)])
no_lam = np.array([0, 0, 0])
  
n = linalg.norm(lam_yz)
print("norm is ",n)
# results for y-polarized
cqed_dict_y = cqed_rhf(lam_y, molstr, options_dict)
# results for z-polarized
cqed_dict_z = cqed_rhf(lam_z, molstr, options_dict)
# results for yz-polarized
cqed_dict_yz = cqed_rhf(lam_yz, molstr, options_dict)
# results for no photon
cqed_dict_no_lam = cqed_rhf(no_lam, molstr, options_dict)


norm is  0.1

Start SCF iterations:

Canonical RHF One-electron energy = -218.2835960115895091
CQED-RHF One-electron energy      = -218.2101311511904953
Nuclear repulsion energy          = 31.7803657982661569
Dipole energy                     = 0.0000000000000000
SCF Iteration   1: Energy = -113.8419924147291340   dE = -1.13842E+02   dRMS = 5.10155E-04
SCF Iteration   2: Energy = -113.8423687079188937   dE = -3.76293E-04   dRMS = 1.83523E-04
SCF Iteration   3: Energy = -113.8423977296978080   dE = -2.90218E-05   dRMS = 8.54020E-05
SCF Iteration   4: Energy = -113.8424016587003393   dE = -3.92900E-06   dRMS = 5.97608E-05
SCF Iteration   5: Energy = -113.8424027104506990   dE = -1.05175E-06   dRMS = 4.58493E-05
SCF Iteration   6: Energy = -113.8424031821128892   dE = -4.71662E-07   dRMS = 3.43800E-05
SCF Iteration   7: Energy = -113.8424034409993340   dE = -2.58886E-07   dRMS = 2.71534E-05
SCF Iteration   8: Energy = -113.8424035918856134   dE = -1.50886E-07   dRMS = 2.06376E-05
SCF Iter

Run the cell below to decompose the changes in CQED-RHF energy to the different 1- and 2-electron
components reported in Table I of McTague and Foley.

In [4]:
print("Delta E \lambda_y:",cqed_dict_y['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY'])
print("Delta E \lambda_z:",cqed_dict_z['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY'])
print("Delta E \lambda_yz:",cqed_dict_yz['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY'])
print('\n')

print("% Delta E 1E \lambda_y:", 100*(cqed_dict_y['1E ENERGY']-cqed_dict_no_lam['1E ENERGY'])/(cqed_dict_y['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 1E \lambda_z:", 100*(cqed_dict_z['1E ENERGY']-cqed_dict_no_lam['1E ENERGY'])/(cqed_dict_z['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 1E \lambda_yz:", 100*(cqed_dict_yz['1E ENERGY']-cqed_dict_no_lam['1E ENERGY'])/(cqed_dict_yz['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print('\n')

print("% Delta E 2E \lambda_y:", 100*(cqed_dict_y['2E ENERGY']-cqed_dict_no_lam['2E ENERGY'])/(cqed_dict_y['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 2E \lambda_z:", 100*(cqed_dict_z['2E ENERGY']-cqed_dict_no_lam['2E ENERGY'])/(cqed_dict_z['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 2E \lambda_yz:", 100*(cqed_dict_yz['2E ENERGY']-cqed_dict_no_lam['2E ENERGY'])/(cqed_dict_yz['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print('\n')

print("% Delta E 1DE \lambda_y:", 100*(cqed_dict_y['1E DIPOLE ENERGY']-cqed_dict_no_lam['1E DIPOLE ENERGY'])/(cqed_dict_y['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 1DE \lambda_z:", 100*(cqed_dict_z['1E DIPOLE ENERGY']-cqed_dict_no_lam['1E DIPOLE ENERGY'])/(cqed_dict_z['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 1DE \lambda_yz:", 100*(cqed_dict_yz['1E DIPOLE ENERGY']-cqed_dict_no_lam['1E DIPOLE ENERGY'])/(cqed_dict_yz['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print('\n')

print("% Delta E 1QE \lambda_y:", 100*(cqed_dict_y['1E QUADRUPOLE ENERGY']-cqed_dict_no_lam['1E QUADRUPOLE ENERGY'])/(cqed_dict_y['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 1QE \lambda_z:", 100*(cqed_dict_z['1E QUADRUPOLE ENERGY']-cqed_dict_no_lam['1E QUADRUPOLE ENERGY'])/(cqed_dict_z['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 1QE \lambda_yz:", 100*(cqed_dict_yz['1E QUADRUPOLE ENERGY']-cqed_dict_no_lam['1E QUADRUPOLE ENERGY'])/(cqed_dict_yz['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print('\n')

print("% Delta E 2DE \lambda_y:", 100*(cqed_dict_y['2E DIPOLE ENERGY']-cqed_dict_no_lam['2E DIPOLE ENERGY'])/(cqed_dict_y['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 2DE \lambda_z:", 100*(cqed_dict_z['2E DIPOLE ENERGY']-cqed_dict_no_lam['2E DIPOLE ENERGY'])/(cqed_dict_z['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E 2DE \lambda_yz:", 100*(cqed_dict_yz['2E DIPOLE ENERGY']-cqed_dict_no_lam['2E DIPOLE ENERGY'])/(cqed_dict_yz['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print('\n')

print("% Delta E Dc \lambda_y:", 100*(cqed_dict_y['DIPOLE ENERGY']-cqed_dict_no_lam['DIPOLE ENERGY'])/(cqed_dict_y['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E Dc \lambda_z:", 100*(cqed_dict_z['DIPOLE ENERGY']-cqed_dict_no_lam['DIPOLE ENERGY'])/(cqed_dict_z['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))
print("% Delta E Dc \lambda_yz:", 100*(cqed_dict_yz['DIPOLE ENERGY']-cqed_dict_no_lam['DIPOLE ENERGY'])/(cqed_dict_yz['CQED-RHF ENERGY']-cqed_dict_no_lam['CQED-RHF ENERGY']))

Delta E \lambda_y: 0.03481836241024894
Delta E \lambda_z: 0.041516621170970325
Delta E \lambda_yz: 0.038132664910165204


% Delta E 1E \lambda_y: -229.48210901359553
% Delta E 1E \lambda_z: -178.80553648867576
% Delta E 1E \lambda_yz: -200.4994691172837


% Delta E 2E \lambda_y: 230.5796433638703
% Delta E 2E \lambda_z: 179.79568126126657
% Delta E 2E \lambda_yz: 201.5926684965595


% Delta E 1DE \lambda_y: -4.4367060983266884e-27
% Delta E 1DE \lambda_z: -31.117230293007097
% Delta E 1DE \lambda_yz: -16.560693129749385


% Delta E 1QE \lambda_y: 209.02318710021623
% Delta E 1QE \lambda_z: 431.26667137951495
% Delta E 1QE \lambda_yz: 329.39574252583697


% Delta E 2DE \lambda_y: -110.12072145077062
% Delta E 2DE \lambda_z: -316.6982010057498
% Delta E 2DE \lambda_yz: -222.20859534013076


% Delta E Dc \lambda_y: 2.488807347715638e-27
% Delta E Dc \lambda_z: 15.558615146503564
% Delta E Dc \lambda_yz: 8.2803465648747


In [5]:
cavity_free_dipole = cqed_dict_no_lam['RHF DIPOLE MOMENT']
polariton_dipole = cqed_dict_yz['CQED-RHF DIPOLE MOMENT']

print(cavity_free_dipole)
print(polariton_dipole)
print(polariton_dipole-cavity_free_dipole)

[ 1.18830650e-15 -3.52252949e-14 -1.00977003e+00]
[ 3.74537366e-15 -2.52730741e-02 -1.05491227e+00]
[ 2.55706716e-15 -2.52730741e-02 -4.51422394e-02]
